task_manager/main_page/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import TaskViewSet, HabitViewSet, CategoryViewSet, RewardViewSet

task_router = DefaultRouter()
task_router.register(r'tasks', TaskViewSet)

habit_router = DefaultRouter()
habit_router.register(r'habits', HabitViewSet)

category_router = DefaultRouter()
category_router.register(r'categories', CategoryViewSet)

reward_router = DefaultRouter()
reward_router.register(r'rewards', RewardViewSet)


urlpatterns = [
    path('', include(task_router.urls)),
    path('', include(habit_router.urls)),
    path('', include(category_router.urls)),
    path('', include(reward_router.urls)),
]

task_manager/main_page/urls.py
from django.urls import path, include
from django.conf.urls.static import static

# from main_page.views import tasks_view, habits_view, logout_view, login_required, categories_view, reward_view, EditProfile, ShowHabit, ShowTask, add_task, add_habit, add_category, complete_task, tasks_archive
import main_page.views as views
from .api import urls as api_urls
from task_manager import settings


app_name = 'main_page'


urlpatterns = [
    path('tasks', views.tasks_view, name='tasks'),
    path('habits', views.habits_view, name='habits'),
    path('dailies', views.tasks_view, kwargs={'is_daily': True}, name='dailies'),
    path('logout', views.logout_view, name='logout'),
    path('categories', views.categories_view, name='categories'),
    path('reward', views.reward_view, name='reward'),
    path('profile/<slug:user_slug>', views.login_required(views.EditProfile.as_view()), name='profile'),
    path('task/<slug:task_slug>', views.login_required(views.ShowTask.as_view()), name='task'),
    path('habit/<slug:habit_slug>', views.login_required(views.ShowHabit.as_view()), name='habit'),
    path('add_task', views.add_task, name='add_task'),
    path('add_daily', views.add_task, kwargs={'is_daily': True}, name='add_daily'),
    path('add_category', views.add_category, name='add_category'),
    path('add_habit', views.add_habit, name='add_habit'),
    path('complete_task/<int:task_id>', views.complete_task, name='complete_task'),
    path('complete_daily/<int:task_id>', views.complete_task, kwargs={'is_daily': True}, name='complete_daily'),
    path('tasks_archive', views.tasks_archive, name='tasks_archive'),
    path('dailies_archive', views.tasks_archive, kwargs={ 'is_daily': True }, name='dailies_archive'),
    path('habit_add/<int:habit_id>', views.habit_control, kwargs={'counter_positive': True}, name='habit_add'),
    path('habit_sub/<int:habit_id>', views.habit_control, kwargs={'counter_positive': False}, name='habit_sub'),
    path('tasks/delete/<int:task_id>', views.login_required(views.delete_task), name='delete_task'),
    path('habits/delete/<int:habit_id>', views.login_required(views.delete_habit), name='delete_habit'),
    path('queries', views.logout_view, name='queries'),

    path('api/v1/', include(api_urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from task_manager import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls')),
    path('', include('main_page.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_manager/main_page/models.py
from django.db import models

# Create your models here.

task_manager/main_page/forms.py
from django.forms import ModelForm

from registration.models import Habit, Task, Category


class HabitForm(ModelForm):
    
    class Meta:
        model = Habit
        fields = ['name',
                  'description',
                  'difficulty',
                  'priority',
                  'categories',
                 ]


class TaskForm(ModelForm):
    
    class Meta:
        model = Task
        fields = ['name',
                  'description',
                  'difficulty',
                  'priority',
                  'categories',
                  ]
        
    def __init__(self, request, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        if request.user:
            self.fields['categories'].queryset = Category.objects.filter(player=request.user)
        

class CategoryForm(ModelForm):

    class Meta:
        model = Category
        fields = [
            'name',
            'description',
        ]

task_manager/main_page/api/views.py
from rest_framework import viewsets

from registration.models import Task, Habit, Category, Reward
from .serializers import TaskSerializer, HabitSerializer, CategorySerializer, RewardSerializer
from .permissions import IsOwner, IsAdminOrReadOnly


class TaskViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    permission_classes = (IsOwner, )

    def perform_create(self, serializer):
        serializer.save(player=self.request.user)

    def get_queryset(self):
        return Task.objects.filter(player=self.request.user)


class HabitViewSet(viewsets.ModelViewSet):
    queryset = Habit.objects.all()
    serializer_class = HabitSerializer
    permission_classes = (IsOwner, )

    def perform_create(self, serializer):
        serializer.save(player=self.request.user)

    def get_queryset(self):
        return Habit.objects.filter(player=self.request.user)
    

class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = (IsOwner, )

    def perform_create(self, serializer):
        serializer.save(player=self.request.user)

    def get_queryset(self):
        return Category.objects.filter(player=self.request.user)


class RewardViewSet(viewsets.ModelViewSet):
    queryset = Reward.objects.all()
    serializer_class = RewardSerializer
    permission_classes = (IsAdminOrReadOnly, )

task_manager/main_page/views.py
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, CreateView, DeleteView
from django.utils.text import slugify
from django.db.models import Prefetch
from django.http import JsonResponse

from .forms import TaskForm, HabitForm, CategoryForm
from registration.models import CustomUser, Category, Reward, Task, Habit
from registration.forms import CustomUserChangeForm


@login_required
def tasks_view(request, is_daily=False):
    user = request.user
    tasks = Task.objects.filter(player=user, is_daily=is_daily, is_completed=False)
    return render(request, 'main_page/tasks.html', { 'user': user, 'tasks': tasks, 'is_daily': is_daily })


@login_required
def habits_view(request):
    user = request.user
    habits = Habit.objects.filter(player=user)
    return render(request, 'main_page/habits.html', { 'user': user, 'habits': habits })


@login_required
def logout_view(request):
    logout(request)
    return redirect('registration:start_page')


@login_required
def categories_view(request):
    user = request.user
    categories = Category.objects.filter(player=user).prefetch_related(
        Prefetch('task_set', queryset=Task.objects.filter(is_completed=False)),
                 'habit_set'
    ).all()

    return render(request, 'main_page/categories.html', { 'categories': categories })


@login_required
def reward_view(request):
    print(request.user.id)
    categories = Category.objects.filter(player=request.user)
    for c in categories:
        print(c.id)
    return HttpResponse("reward")


class EditProfile(UpdateView):
    model = CustomUser
    template_name = 'main_page/profile.html'
    fields = ['first_name', 'profile_pic', ]

    def form_valid(self, form):
        form.save()
        return redirect('main_page:tasks')

    def get_object(self, queryset=None):
        slug = self.kwargs['user_slug']
        return get_object_or_404(CustomUser, slug=slug)


class ShowTask(UpdateView):
    model = Task
    template_name = 'main_page/show_task.html'
    fields = [ 'name', 'description', 'difficulty', 'due_date', 'categories', 'is_daily' ]

    def get_object(self, queryset=None):
        slug = self.kwargs['task_slug']
        return get_object_or_404(Task, slug=slug)
    
    def form_valid(self, form):
        form.save()
        return redirect('main_page:tasks')
    

class ShowHabit(UpdateView):
    model = Habit
    template_name = 'main_page/show_habit.html'
    fields = [ 'name', 'description', 'categories' ]

    def get_object(self, queryset=None):
        slug = self.kwargs['habit_slug']
        return get_object_or_404(Habit, slug=slug)
    
    def form_valid(self, form):
        form.save()
        return redirect('main_page:habits')


@login_required
def add_task(request, is_daily=False):
    task_type = 'DAILY' if is_daily else 'TASK'
    
    if request.method == 'POST':
        form = TaskForm(request, request.POST)
        success_url = reverse('main_page:tasks')
        if form.is_valid():
            task = form.save(commit=False)
            task.player = request.user
            task.reward = 2.0*task.priority + task.difficulty
            task.is_daily = is_daily
            test_slug = slugify(task.name)
            i = 1

            while True:
                try:
                    Task.objects.get(slug=test_slug)
                    test_slug = f"{slugify(task.name)}-{i}"
                    i += 1
                except Task.DoesNotExist:
                    task.slug = test_slug
                    break

            if is_daily:
                success_url = reverse('main_page:dailies')
            task.save()
            form.save_m2m()
            return redirect(success_url)
    else:
        form = TaskForm(request)
    
    return render(request, 'main_page/add_task.html', {'form': form, 'task_type': task_type, })


@login_required    
def add_habit(request):
    if request.method == 'POST':
        form = HabitForm(request.POST)
        success_url = reverse('main_page:habits')
        if form.is_valid():
            habit = form.save(commit=False)
            habit.player = request.user
            habit.reward = 2.0*habit.priority + habit.difficulty 
            test_slug = slugify(habit.name)
            i = 1
            
            while True:
                try:
                    Habit.objects.get(slug=test_slug)
                    test_slug = f"{slugify(habit.name)}-{i}"
                    i += 1
                except Habit.DoesNotExist:
                    habit.slug = test_slug
                    break
            
            habit.save()
            form.save_m2m()
            return redirect(success_url)
    else:
        form = HabitForm()
    
    return render(request, 'main_page/add_habit.html', {'form': form})


@login_required
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        success_url = reverse('main_page:categories')
        if form.is_valid():
            category = form.save(commit=False)
            category.player = request.user
            category.save()
            return redirect(success_url)
        
    else:
        form = CategoryForm()

    return render(request, 'main_page/add_category.html', {'form': form})



@login_required
def complete_task(request, task_id, is_daily=False):
    if request.method == 'POST':
        task = get_object_or_404(Task, id=task_id)
        user = request.user
        categories = task.categories.all()

        m = -1 if task.is_completed else 1
        for c in categories:
            c.progress_meter += task.reward * m
            c.save()
        user.currency_amount += task.reward * m
        user.save()
        task.is_completed = request.POST.get('is_completed') == 'true'            
        task.completion_count += m
        task.save()
        return JsonResponse({'completed': task.is_completed})
    else:
        return JsonResponse({'completed': False})


@login_required
def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    return redirect(reverse('main_page:tasks'))


@login_required
def delete_habit(request, habit_id):
    habit = get_object_or_404(Habit, id=habit_id)
    habit.delete()
    return redirect(reverse('main_page:habits'))


@login_required
def tasks_archive(request, is_daily=False): 
    user = request.user
    tasks = Task.objects.filter(player=user, is_daily=is_daily, is_completed=True)
    return render(request, 'main_page/tasks_archive.html',
                  { 'user': user, 'tasks': tasks, 'is_daily': is_daily })    


@login_required
def habit_control(request, habit_id, counter_positive=True):    
    if request.method == 'POST':
        habit = get_object_or_404(Habit, id=habit_id)
        user = request.user
        categories = habit.categories.all()

        if counter_positive:
            m = 1
            habit.tracking_meter = min(habit.tracking_meter + habit.reward, 100)
        else:
            m = -1
            habit.tracking_meter = max(habit.tracking_meter - habit.reward, -100)
        for c in categories:
            c.progress_meter += habit.reward * m
            c.save()
        user.currency_amount += habit.reward * m
        user.save()
        habit.save()
        return JsonResponse({'currency_amount': user.currency_amount, 'lvl': user.lvl})
    else:
        return JsonResponse()

task_manager/main_page/templates/main_page/achievements.html
{% extends 'base.html' %}


{% block title %} 

<title>Achievements</title> 

{% endblock %}


{% block content %}


{% endblock %}

task_manager/main_page/templates/main_page/add_category.html
{% extends 'forms_base.html' %}

{% load static %}
{% load django_bootstrap5 %}


{% block title %} 

<title>Add Category</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/add-item-form-page.css' %}">

{% endblock %}


{% block content %}

<div class="container-m align-items-center">
<h1>ADD CATEGORY</h1>
  
  <form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

{% endblock %}

task_manager/main_page/templates/main_page/categories.html
{% extends 'base.html' %}

{% load static %}


{% block title %}

<title>Categories</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/categories.css' %}">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/checkbox_script.js' %}"></script>

{% endblock %}


{% block content %}

<div class="container bg-light main-container">
    <h2 class="text-center">Categories</h2>
    <a href="{% url 'main_page:add_category' %}" class="btn btn-light btn-lg btn-hover add-category">Add Category</a>
    <div class="accordion accordion-flush" id="accordionFlushExample">
        {% for c in categories %}
        <div class="accordion-item">
          <h2 class="accordion-header" id="flush-heading{{ c.id }}">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{ c.id }}" aria-expanded="false" aria-controls="flush-collapse{{ c.id }}">
                {{ c.name }}
            </button>
          </h2>
          <div id="flush-collapse{{ c.id }}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{ c.id }}" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body"> 
              <h3 class="text-center title-h3">Tasks</h3>
              {% for t in c.task_set.all %}
              {% if t.is_daily == False %}
                <div class="container-text-left subcontainer">
                    <div class="row list-items">
                        <div class="col-5 align-items-center justify-content-center"><h3>{{ t.name }}</h3></div>
                        {% if t.description %}
                        <div class="col align-items-center justify-content-center"><h3>{{ t.description }}</h3></div>
                        {% else %}
                        <div class="col align-items-center justify-content-center"><h3> </h3></div>
                        {% endif %}

                        <div class="col-1 d-flex align-items-center justify-content-center">
                        
                        <img src="media/images/edit_icon.png" class="icons" onclick='location.href="{{ t.get_absolute_url }}"'>
                        <input type="checkbox" {% if t.is_completed %}checked{% endif %} data-url="{{ t.get_completion_url }}" data-csrf="{{ csrf_token }}" class="task-checkbox">
                        
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}   

                <h3 class="text-center title-h3">Dailies</h3>
                {% for d in c.task_set.all %}
                {% if d.is_daily == True %}
                <div class="container-text-left subcontainer">
                    <div class="row list-items">
                        <div class="col-5 align-items-center justify-content-center"><h3>{{ d.name }}</h3></div>
                        {% if d.description %}
                        <div class="col align-items-center justify-content-center"><h3>{{ d.description }}</h3></div>
                        {% else %}
                        <div class="col align-items-center justify-content-center"><h3> </h3></div>
                        {% endif %}

                        <div class="col-1 d-flex align-items-center justify-content-center">
                        {% block icons %}
                        <img class="icons" src="media/images/edit_icon.png" onclick='location.href="{{ d.get_absolute_url }}"'>
                        <input type="checkbox" {% if d.is_completed %}checked{% endif %} data-url="{{ d.get_completion_url }}" data-csrf="{{ csrf_token }}" class="task-checkbox">
                        {% endblock %}
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}

                <h3 class="text-center title-h3">Habits</h3>
                {% for h in c.habit_set.all %}
                <div class="container-text-left subcontainer">
                    <div class="row list-items">
                        <div class="col-5 align-items-center justify-content-center"><h3>{{ h.name }}</h3></div>
                        {% if h.description %}
                        <div class="col align-items-center justify-content-center"><h3>{{ h.description }}</h3></div>
                        {% else %}
                        <div class="col align-items-center justify-content-center"><h3> </h3></div>
                        {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
          </div>
        </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

task_manager/main_page/templates/main_page/habits.html
{% extends 'main_page/tasks.html' %}

{% load static %}


{% block title %} 

<title>Habits</title> 
<link rel="stylesheet" type="text/css" href="{% static 'css/main_pages.css' %}">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/habit_controls.js' %}"></script>

{% endblock %}


{% block items_list %}

<div class="btn-group btn-light d-flex main-container" role="group" aria-label="Basic example">
    <button type="button" class="btn btn-secondary btn-light btn-hover btn-lg" onclick="location.href=`{% url 'main_page:tasks' %}`">Tasks</button>
    <button type="button" class="btn btn-secondary btn-light btn-hover btn-lg active" style="pointer-events: none;">Habits</button>
    <button type="button" class="btn btn-secondary btn-light btn-hover btn-lg" onclick="location.href=`{% url 'main_page:dailies' %}`">Dailies</button>
</div>

<div class="container-text-left content-container">
    <div class="row">
        <a href="{% url 'main_page:add_habit' %}" class="btn btn-light btn-lg btn-hover">Add Habit</a>       
    </div>

    {% for h in habits %}
        <div class="row iter-rows">
            <div class="col-5 align-items-center justify-content-center"><h3 class="labels">{{ h.name }}</h3></div>
            <div class="col align-items-center justify-content-center"><h3 class="labels">{{ h.description }}</h3></div>
            <div class="col-2 d-flex align-items-center justify-content-center">
                <img src="media/images/edit_icon.png" class="edit-icon" onclick='location.href="{{ h.get_absolute_url }}"'>
                <a href="#" class="btn btn-lg btn-hover habit-controls" data-url="{{ h.get_add_url }}" data-csrf="{{ csrf_token }}">+</a>
                <a href="#" class="btn btn-lg btn-hover habit-controls" data-url="{{ h.get_sub_url }}" data-csrf="{{ csrf_token }}">-</a>
                <img src="media/images/delete_item_icon.png" class="edit-icon" onclick='location.href="{{ h.get_deletion_url }}"'>
            </div>
        </div>
    {% endfor %}
    
</div>

{% endblock %}

task_manager/main_page/templates/main_page/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} <title>Task Manager Project</title> {% endblock %}

{% block content %}
<div class="container text-center" style="margin-top: 50px;">
    <div class="row">
      <div class="col d-flex justify-content-center align-items-center">
        <h1>LVL {{ user.lvl }}</h1>
      </div>
      <div class="col d-flex justify-content-center align-items-center">
        <div class="d-flex justify-content-center align-items-center">
            <img src='media/images/coin_icon.png' style="border-radius: 50%; width: auto; max-height: 20px; float: left; padding-right: 5px;">
            <h1>{{ user.currency_amount}} </h1>
        </div>
      </div>
      <div class="col">
        <img src="{{ user.profile_pic.url }}" style="border-radius: 50%; width: auto; max-height: 100px; cursor: pointer" onclick="location.href=`{% url 'main_page:profile' %}`">
      </div>
      <div class="col d-flex justify-content-center align-items-center">
        <a href="{% url 'main_page:achievements' %}" style="font-size: calc(1.375rem + 1vw);;
        color: #333;
        margin: 0;
        padding: 0;
        text-decoration: none;">Achievements</a>
      </div>
      <div class="col d-flex justify-content-center align-items-center">
        <a href="{% url 'main_page:categories' %}" style="font-size: calc(1.375rem + 1vw);
        color: #333;
        margin: 0;
        padding: 0;
        text-decoration: none;">Categories</a>
      </div>
    </div>
</div>


<div class="btn-group btn-light d-flex" role="group" aria-label="Basic example" style="margin-top: 50px;">
  {% block menu %}
  <button type="button" class="btn btn-secondary btn-light btn-hover btn-lg active" style="pointer-events: none;">Tasks</button>
  <button type="button" class="btn btn-secondary btn-light btn-hover btn-lg" onclick="location.href=`{% url 'main_page:habits' %}`">Habits</button>
  <button type="button" class="btn btn-secondary btn-light btn-hover btn-lg" onclick="location.href=`{% url 'main_page:dailies' %}`">Dailies</button>
  {% endblock %}
</div>

<div class="container-text-left" style="margin-left: 12px; margin-right: 12px; margin-top: 10px;">
  <div class="row">
  <a href="#" class="btn btn-light btn-lg btn-hover" onclick="location.href=`{% url 'main_page:add_task' %}`">Add Task</a>       
  </div>
  {% for t in tasks %}
  <div class="row" style="margin-top: 10px;">
    <div class="col-5 align-items-center justify-content-center"><h3 style="float: left;">{{ t.name }}</h3></div>
    <div class="col align-items-center justify-content-center"><h3 style="float: left;">{{ t.description }}</h3></div>
    <div class="col-1 d-flex align-items-center justify-content-center">
      <img src="media/images/edit_icon.png" style="width: 20px; max-height: 20px; float: right; margin-right: 30px; cursor: pointer" onclick='location.href="{{ t.get_absolute_url }}"'>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

task_manager/main_page/templates/main_page/show_habit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Habit</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        {{form.errors}}
        <button type="submit">Save</button>
    </form>
</body>
</html>

task_manager/main_page/templates/main_page/tasks.html
{% extends 'base.html' %}

{% load static %}


{% block title %} 

<title>Task Manager Project</title>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/checkbox_script.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/main_pages.css' %}">

{% endblock %}


{% block content %}

<div class="container text-center main-container">
  <a class="btn position-absolute top-0 start-0 sidebar-anchor" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
    <img src="media/images/sidebar_icon.png" class="sidebar-icon" alt="Sidebar">
  </a>
  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasExampleLabel">Navigation</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <ul class="list-group">
      <li class="list-group-item" aria-current="true">
        <a href="{% url 'main_page:logout' %}" class="btn btn-hover">Log Out</a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'main_page:queries' %}" class="btn btn-hover">Query Tools</a>
      </li>
    </ul>
  </div>

  <div class="row">
    <div class="col d-flex justify-content-center align-items-center">
      <h1 id="lvl">LVL {{ user.lvl }}</h1>
    </div>
    <div class="col d-flex justify-content-center align-items-center">
      <div class="d-flex justify-content-center align-items-center">
          <img src='media/images/coin_icon.png' class="navbar-icon">
          <h1 id="currency-amount">{{ user.currency_amount}} </h1>
      </div>
    </div>
    <div class="col">
      <img src="{{ user.profile_pic.url }}" class="pfp-icon" onclick="location.href=`{{user.get_absolute_url}}`">
    </div>
    <div class="col d-flex justify-content-center align-items-center">
      <a href="{% url 'main_page:reward' %}" class="navbar-links">Rewards</a>
    </div>
    <div class="col d-flex justify-content-center align-items-center">
      <a href="{% url 'main_page:categories' %}" class="navbar-links">Categories</a>
    </div>
  </div>
</div>


{% block items_list %}

<div class="btn-group btn-light d-flex main-container" role="group" aria-label="Basic example">

{% block navbar %}
  {% if is_daily == False %}
    <button type="button" class="btn btn-secondary btn-light btn-hover btn-lg active" style="pointer-events: none;">Tasks</button>
    <button type="button" class="btn btn-secondary btn-light btn-hover btn-lg" onclick="location.href=`{% url 'main_page:habits' %}`">Habits</button>
    <button type="button" class="btn btn-secondary btn-light btn-hover btn-lg" onclick="location.href=`{% url 'main_page:dailies' %}`">Dailies</button>
  {% else %}
    <button type="button" class="btn btn-secondary btn-light btn-hover btn-lg" onclick="location.href=`{% url 'main_page:tasks' %}`">Tasks</button>
    <button type="button" class="btn btn-secondary btn-light btn-hover btn-lg" onclick="location.href=`{% url 'main_page:habits' %}`">Habits</button>
    <button type="button" class="btn btn-secondary btn-light btn-hover btn-lg active" style="pointer-events: none;">Dailies</button>
  {% endif %}

{% endblock %}

</div>


<div class="container-text-left content-container">
  <div class="row">
  {% if not is_daily %}
    <a href="{% url 'main_page:add_task' %}" class="btn btn-light btn-lg btn-hover">Add Task</a>       
  {% else %}
    <a href="{% url 'main_page:add_daily' %}" class="btn btn-light btn-lg btn-hover">Add Daily</a>       
  {% endif %}
  </div>

  {% for t in tasks %}

  <div class="row iter-rows">
    <div class="col-5 align-items-center justify-content-center"><h3 class="labels">{{ t.name }}</h3></div>
    {% if t.description %}
      <div class="col align-items-center justify-content-center"><h3 class="labels">{{ t.description }}</h3></div>
    {% else %}
      <div class="col align-items-center justify-content-center"><h3 class="labels"> </h3></div>
    {% endif %}

    <div class="col-1 d-flex align-items-center justify-content-center">
      {% block icons %}
      <img src="media/images/edit_icon.png" class="edit-icon" onclick='location.href="{{ t.get_absolute_url }}"'>
      <input type="checkbox" {% if t.is_completed %}checked{% endif %} data-url="{{ t.get_completion_url }}" data-csrf="{{ csrf_token }}" class="task-checkbox">
      <img src="media/images/delete_item_icon.png" class="edit-icon" onclick='location.href="{{ t.get_deletion_url }}"'>
      {% endblock %}
    </div>

  </div>
  
  {% endfor %}

  <div class="row"> 
    {% block archive_link %}

    {% if is_daily == False %}
      <a href="{% url 'main_page:tasks_archive' %}" class="btn btn-lg btn-hover">Archive</a>
    {% else %}
      <a href="{% url 'main_page:dailies_archive' %}" class="btn btn-lg btn-hover">Archive</a>
    {% endif %}
    
    {% endblock %}
  </div>
</div>



{% endblock %}


{% endblock %}